### ISSUE TITLE
organizationId & organizationUserId empty in invitation mail

### ISSUE THREAD

**Issue by Fe3lApAcUt** [sirtoobii/vaultwarden_ldap_sync#2]
When receiving the invitation mail the organizationId & organizationUserId parameters are empty. I think this is because there is no way to configure the organization, right? If so, would it be possible to add a default org to the .env-file or is this not intended? 
The "Invitation organization name" in the admin panel is set. 

https://vw.xxx.xxx/#/accept-organization/?organizationId=**_**&organizationUserId=**_**&email=helpdesk%40xxx%2Ech&organizationName=xxx%20xxx

BR Marcel

**Comment by sirtoobii** [comment]
Invitation emails are sent by Vaultwarden directly - if I recall correctly, this setting can be set somewhere in the VaultWarden config.

**Comment by Fe3lApAcUt** [comment]
Yeah, thanks. Just saw this. Even if i invite a user via VW functionality the parameters are blank. 
BW directory connector let you choose which org id and client secret to use. 

So, no issue here.
