### ISSUE TITLE
Invite user not starting 

### ISSUE THREAD

**Issue by GaetanJeff** [sirtoobii/vaultwarden_ldap_sync#6]
I have deployed a vaultwarden and a vaultwarden_ldap_sync but my vaultwarden_ldap_sync doesn't invite members even though it co well and the messages say invited but when I go to the vaultwarden admin panel nothing.

![image](https://github.com/sirtoobii/vaultwarden_ldap_sync/assets/30666743/1cec96c9-3c38-4d5e-b6b0-c2767b0fb65c)

**Comment by sirtoobii** [comment]
Hi @GaetanJeff  let me guess ;)
 https://github.com/sirtoobii/vaultwarden_ldap_sync/blob/316c4a0f812c648b3a04e578ddf5a2a6a348f03d/.env.dist#L41
